- hosts: frontends
  gather_facts: false
  tasks:
  - name: curl check webpage
    uri:
     url: "http://{{ item }}"
     return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: webpage

  - name: Check and fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
